### ISSUE TITLE
Code kan niet worden geupload

### ISSUE THREAD

**Issue by HvO-student** [Shorts1999/ArexxGameBoard#2]
### **Probleem:**

de code upload niet en onderstaande error wordt genereert:

![afbeelding](https://user-images.githubusercontent.com/112987855/199740449-3c401410-d438-4b76-84c9-0b0496b031a4.png)

### **Oplossing:**
Dit is een bug in versie 2.0.4 van de arduino-espressif32 framework, pas in de platform.ini file het volgende aan:
platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.3

dit zou het probleem op moeten oplossen!

**Comment by Shorts1999** [comment]
Version rollback to 2.0.3 implemented in [fae3f2d](https://github.com/Shorts1999/ArexxGameBoard/commit/fae3f2dc443861e80d6f8092c3757073d1ec3d5a)

Thanks!
